apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-traefik

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    releaseName: traefik
    valuesFile: values.yaml
    version: v35.2.0

resources:
  - namespace.yaml
  - ingress.yaml
